---
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DeployStack:
    Type: String
    Default: ""
    AllowedValues:
      - true
      - ""

Conditions:
  FullDeploy:
    Fn::Equals:
      - !Ref DeployStack
      - true

Resources:
  DeployBucket:
    Type: AWS::S3::Bucket

  CljsRuntime:
    Condition: FullDeploy
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content: ./runtime

  CljsHandler:
    Condition: FullDeploy
    Type: AWS::Lambda::Function
    Properties:
      Handler: example.handler/-main
      Role: !GetAtt LambdaRole.Arn
      Runtime: provided
      Code: ./handler
      MemorySize: 1024
      Layers:
        - !Ref CljsRuntime

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
