#!/bin/sh

set -euo pipefail

$LAMBDA_TASK_ROOT/node_modules/lumo-cljs/bin/lumo \
  -e "$(cat handler.cljs)"

# Execute the handler function from the script
# RESPONSE=$(./node_modules/lumo-cljs/bin/lumo -m $_HANDLER "$EVENT_DATA")
